projects:
  amplifyreactapp:
    schemaPath: src/graphql/schema.json
    includes:
      - graph
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
